let bookingList = [
    {
        id: '001',
        key: 'valaki',
        booking_ubication: 'Valaki, Barovia',
        card_description: 'House near the church',
        detail_description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at massa non est egestas semper. Vestibulum et orci nulla. Donec ac pharetra mauris. Nulla eget tellus tortor. Nam ac urna fermentum, ultricies dolor in, porta mi. Vivamus consectetur et justo non facilisis. Morbi facilisis pretium velit, ut scelerisque nisi tristique sed. Pellentesque pretium ex eu eros pulvinar, eu eleifend nisi iaculis. Aliquam at eros ut massa suscipit porta sit amet at magna. Nullam aliquet justo leo, nec dapibus nibh egestas aliquam. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Integer aliquet enim vitae est vestibulum commodo in at ante. Donec convallis mattis leo vel condimentum. Maecenas nec lectus nec ex semper egestas ac vitae quam. Nam et vestibulum velit. Morbi massa elit, iaculis lacinia ante a, aliquet pharetra felis. Quisque pharetra vulputate dapibus. Vestibulum vulputate viverra elit, ac euismod risus tempor sed. Donec eros libero, luctus eu mi et, malesuada pharetra nulla. Praesent tempor bibendum massa, at faucibus odio cursus pellentesque. Aenean a congue dui. Donec consequat aliquet felis, ut tincidunt turpis feugiat at. Donec purus lacus, iaculis vitae lacus non, consectetur volutpat odio. Nulla cursus nisi vel egestas faucibus Fusce vel vehicula eros. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus maximus nibh odio, ac fermentum risus maximus vulputate. Praesent rutrum, dui at eleifend pellentesque, felis dui consectetur turpis, at venenatis tortor est vel purus. Duis dolor enim, malesuada in ante nec, egestas laoreet lectus. Aliquam erat volutpat. Aenean vel velit ac elit gravida tincidunt. Donec felis libero, faucibus vel sapien in, rutrum dignissim eros. Maecenas fermentum ornare erat, sit amet suscipit est ultrices quis. Morbi ornare, magna id posuere tempor, lacus eros viverra dolor, vel scelerisque lectus erat eu dolor. Sed pulvinar elementum malesuada. ',
        host: 'Blinsky',
        cardImages: require('../assets/bookingsimg/blinskyhouse1.jpg'),
        characteristics:[{
            beds:'two beds',
            bathroom:'exclusive bathroom',
            work_area:'work area',
            shared_area:'shared area'
        }],
        afterBookingData: [{
            first_notification: '',
            morning_notifications: ['', ''],
            lunch_notifications: ['', ''],
            afternoon_notifications: ['', ''],
            dinner_notifications: ['', ''],
            sunset_notifications: ['', ''],
            evening_notifications: ['', ''],
            midnight_notifcations: ['', ''],
            early_morning: ['', ''],
        }],
    },
    {
        id: '002',
        key: 'minas tirith',
        booking_ubication: 'Minas Tirith',
        card_description: 'Second level of the citadel',
        detail_description: '',
        host: 'Guardia de Gondor',
        cardImages: require('../assets/bookingsimg/minastirithhouse.jpg'),
        afterBookingData: [{
            first_notification: '',
            morning_notifications: ['', ''],
            lunch_notifications: ['', ''],
            afternoon_notifications: ['', ''],
            dinner_notifications: ['', ''],
            sunset_notifications: ['', ''],
            evening_notifications: ['', ''],
            midnight_notifcations: ['', ''],
            early_morning: ['', ''],
        }]
    }, {
        id: '003',
        key: 'narshe',
        booking_ubication: 'Narshe',
        card_description: 'My place at Narshe Mines',
        detail_description: '',
        host: 'Moogle',
        cardImages: require('../assets/bookingsimg/narshe1.jpg'),
        afterBookingData: [{
            first_notification: '',
            morning_notifications: ['', ''],
            lunch_notifications: ['', ''],
            afternoon_notifications: ['', ''],
            dinner_notifications: ['', ''],
            sunset_notifications: ['', ''],
            evening_notifications: ['', ''],
            midnight_notifcations: ['', ''],
            early_morning: ['', ''],
        }]
    }, {
        id: '004',
        key: 'medina village',
        booking_ubication: 'Medina Village',
        card_description: 'Casa del anciano',
        detail_description: '',
        host: 'Descendiente de Vinnie',
        cardImages: require('../assets/bookingsimg/medinahouse1.png'),
        afterBookingData: [{
            first_notification: '',
            morning_notifications: ['', ''],
            lunch_notifications: ['', ''],
            afternoon_notifications: ['', ''],
            dinner_notifications: ['', ''],
            sunset_notifications: ['', ''],
            evening_notifications: ['', ''],
            midnight_notifcations: ['', ''],
            early_morning: ['', ''],
        }]
    }, {
        id: '005',
        key: 'revachol',
        booking_ubication: 'Martinaise, Revachol',
        card_description: 'little House at the fishermen shacks',
        detail_description: '',
        host: 'Old Woman',
        cardImages: require('../assets/bookingsimg/fishermenshackshouse1.jpg'),
        afterBookingData: [{
            first_notification: '',
            morning_notifications: ['', ''],
            lunch_notifications: ['', ''],
            afternoon_notifications: ['', ''],
            dinner_notifications: ['', ''],
            sunset_notifications: ['', ''],
            evening_notifications: ['', ''],
            midnight_notifcations: ['', ''],
            early_morning: ['', ''],
        }]
    }, {
        id: '006',
        key: 'fukai',
        booking_ubication: 'Sea of decay',
        card_description: 'Underneath fukai',
        detail_description: '',
        host: 'Nausicaä',
        cardImages: require('../assets/bookingsimg/belowfukai1.jpg'),
        afterBookingData: [{
            first_notification: '',
            morning_notifications: ['', ''],
            lunch_notifications: ['', ''],
            afternoon_notifications: ['', ''],
            dinner_notifications: ['', ''],
            sunset_notifications: ['', ''],
            evening_notifications: ['', ''],
            midnight_notifcations: ['', ''],
            early_morning: ['', ''],
        }]
    }, {
        id: '007',
        key: 'torre bellsprout',
        booking_ubication: 'Violet City',
        card_description: 'Bellsprout tower',
        detail_description: '',
        host: 'Monk of bellsprout tower',
        cardImages: require('../assets/bookingsimg/bellsprouttower1.jpg'),
        afterBookingData: [{
            first_notification: '',
            morning_notifications: ['', ''],
            lunch_notifications: ['', ''],
            afternoon_notifications: ['', ''],
            dinner_notifications: ['', ''],
            sunset_notifications: ['', ''],
            evening_notifications: ['', ''],
            midnight_notifcations: ['', ''],
            early_morning: ['', ''],
        }]
    }, {
        id: '008',
        key: '008',
        booking_ubication: 'Central City',
        card_description: 'Apartment at Central city downtown in Amestris',
        detail_description: '',
        host: 'Benjamin Westcott',
        cardImages: require('../assets/bookingsimg/centralcityalchemist.jpg'),
        afterBookingData: [{
            first_notification: '',
            morning_notifications: ['', ''],
            lunch_notifications: ['', ''],
            afternoon_notifications: ['', ''],
            dinner_notifications: ['', ''],
            sunset_notifications: ['', ''],
            evening_notifications: ['', ''],
            midnight_notifcations: ['', ''],
            early_morning: ['', ''],
        }]
    }, {
        id: '009',
        key: '009',
        booking_ubication: 'Rukongai',
        card_description: 'Beautiful house for staying while visiting Soul Society',
        detail_description: '',
        host: 'Renjiro Fujiwara',
        cardImages: require('../assets/bookingsimg/rukongai1/rukongai2.jpg'),
        afterBookingData: [{
            first_notification: '',
            morning_notifications: ['', ''],
            lunch_notifications: ['', ''],
            afternoon_notifications: ['', ''],
            dinner_notifications: ['', ''],
            sunset_notifications: ['', ''],
            evening_notifications: ['', ''],
            midnight_notifcations: ['', ''],
            early_morning: ['', ''],
        }]
    },
    {
        id: '010',
        key: '010',
        booking_ubication: 'Trost',
        card_description: "Stunning views in Trost, just beware of lurking Titans. Unforgettable stay with a thrilling twist!",
        detail_description: '',
        host: 'Anika Fischer',
        cardImages: require('../assets/bookingsimg/trost1/trost1.jpg'),
        afterBookingData: [{
            first_notification: '',
            morning_notifications: ['', ''],
            lunch_notifications: ['', ''],
            afternoon_notifications: ['', ''],
            dinner_notifications: ['', ''],
            sunset_notifications: ['', ''],
            evening_notifications: ['', ''],
            midnight_notifcations: ['', ''],
            early_morning: ['', ''],
        }]
    }]

export default bookingList