let bookingList = [
    {
        id: '001',
        key: 'valaki',
        booking_ubication: 'Valaki',
        card_description: 'House near the church',
        detail_description: '',
        host: 'Blinsky',
        cardImages: require('../assets/bookingsimg/blinskyhouse1.jpg'),
        afterBookingData: [{
            first_notification: '',
            morning_notifications: ['', ''],
            lunch_notifications: ['', ''],
            afternoon_notifications: ['', ''],
            dinner_notifications: ['', ''],
            sunset_notifications: ['', ''],
            evening_notifications: ['', ''],
            midnight_notifcations: ['', ''],
            early_morning: ['', ''],
        }],
    },
    {
        id: '002',
        key: 'minas tirith',
        booking_ubication: 'Minas Tirith',
        card_description: 'Second level of the citadel',
        detail_description: '',
        host: 'Guardia de Gondor',
        cardImages: require('../assets/bookingsimg/minastirithhouse.jpg'),
        afterBookingData: [{
            first_notification: '',
            morning_notifications: ['', ''],
            lunch_notifications: ['', ''],
            afternoon_notifications: ['', ''],
            dinner_notifications: ['', ''],
            sunset_notifications: ['', ''],
            evening_notifications: ['', ''],
            midnight_notifcations: ['', ''],
            early_morning: ['', ''],
        }]
    }, {
        id: '003',
        key: 'narshe',
        booking_ubication: 'Narshe',
        card_description: 'My place at Narshe Mines',
        detail_description: '',
        host: 'Moogle',
        cardImages: require('../assets/bookingsimg/narshe1.jpg'),
        afterBookingData: [{
            first_notification: '',
            morning_notifications: ['', ''],
            lunch_notifications: ['', ''],
            afternoon_notifications: ['', ''],
            dinner_notifications: ['', ''],
            sunset_notifications: ['', ''],
            evening_notifications: ['', ''],
            midnight_notifcations: ['', ''],
            early_morning: ['', ''],
        }]
    }, {
        id: '004',
        key: 'medina village',
        booking_ubication: 'Medina Village',
        card_description: 'Casa del anciano',
        detail_description: '',
        host: 'Descendiente de Vinnie',
        cardImages: require('../assets/bookingsimg/medinahouse1.png'),
        afterBookingData: [{
            first_notification: '',
            morning_notifications: ['', ''],
            lunch_notifications: ['', ''],
            afternoon_notifications: ['', ''],
            dinner_notifications: ['', ''],
            sunset_notifications: ['', ''],
            evening_notifications: ['', ''],
            midnight_notifcations: ['', ''],
            early_morning: ['', ''],
        }]
    }, {
        id: '005',
        key: 'revachol',
        booking_ubication: 'Martinaise, Revachol',
        card_description: 'little House at the fishermen shacks',
        detail_description: '',
        host: 'Old Woman',
        cardImages: require('../assets/bookingsimg/fishermenshackshouse1.jpg'),
        afterBookingData: [{
            first_notification: '',
            morning_notifications: ['', ''],
            lunch_notifications: ['', ''],
            afternoon_notifications: ['', ''],
            dinner_notifications: ['', ''],
            sunset_notifications: ['', ''],
            evening_notifications: ['', ''],
            midnight_notifcations: ['', ''],
            early_morning: ['', ''],
        }]
    }, {
        id: '006',
        key: 'fukai',
        booking_ubication: 'Sea of decay',
        card_description: 'Underneath fukai',
        detail_description: '',
        host: 'Nausicaä',
        cardImages: require('../assets/bookingsimg/belowfukai1.jpg'),
        afterBookingData: [{
            first_notification: '',
            morning_notifications: ['', ''],
            lunch_notifications: ['', ''],
            afternoon_notifications: ['', ''],
            dinner_notifications: ['', ''],
            sunset_notifications: ['', ''],
            evening_notifications: ['', ''],
            midnight_notifcations: ['', ''],
            early_morning: ['', ''],
        }]
    }, {
        id: '007',
        key: 'torre bellsprout',
        booking_ubication: 'Violet City',
        card_description: 'Bellsprout tower',
        detail_description: '',
        host: 'Monk of bellsprout tower',
        cardImages: require('../assets/bookingsimg/bellsprouttower1.jpg'),
        afterBookingData: [{
            first_notification: '',
            morning_notifications: ['', ''],
            lunch_notifications: ['', ''],
            afternoon_notifications: ['', ''],
            dinner_notifications: ['', ''],
            sunset_notifications: ['', ''],
            evening_notifications: ['', ''],
            midnight_notifcations: ['', ''],
            early_morning: ['', ''],
        }]
    }, {
        id: '008',
        key: '008',
        booking_ubication: 'Central City',
        card_description: 'Apartment at Central city downtown in Amestris',
        detail_description: '',
        host: 'Benjamin Westcott',
        cardImages: '',
        afterBookingData: [{
            first_notification: '',
            morning_notifications: ['', ''],
            lunch_notifications: ['', ''],
            afternoon_notifications: ['', ''],
            dinner_notifications: ['', ''],
            sunset_notifications: ['', ''],
            evening_notifications: ['', ''],
            midnight_notifcations: ['', ''],
            early_morning: ['', ''],
        }]
    }, {
        id: '009',
        key: '009',
        booking_ubication: 'Rukongai',
        card_description: 'Beautiful house for staying while visiting Soul Society',
        detail_description: '',
        host: 'Renjiro Fujiwara',
        cardImages: "",
        afterBookingData: [{
            first_notification: '',
            morning_notifications: ['', ''],
            lunch_notifications: ['', ''],
            afternoon_notifications: ['', ''],
            dinner_notifications: ['', ''],
            sunset_notifications: ['', ''],
            evening_notifications: ['', ''],
            midnight_notifcations: ['', ''],
            early_morning: ['', ''],
        }]
    },
    {
        id: '010',
        key: '010',
        booking_ubication: 'Trost',
        card_description: "Stunning views in Trost, just beware of lurking Titans. Unforgettable stay with a thrilling twist!",
        detail_description: '',
        host: 'Anika Fischer',
        cardImages: "",
        afterBookingData: [{
            first_notification: '',
            morning_notifications: ['', ''],
            lunch_notifications: ['', ''],
            afternoon_notifications: ['', ''],
            dinner_notifications: ['', ''],
            sunset_notifications: ['', ''],
            evening_notifications: ['', ''],
            midnight_notifcations: ['', ''],
            early_morning: ['', ''],
        }]
    }]

export default bookingList